
spring:
  thymeleaf:
    prefix: classpath:/templates/html/
    suffix: .html
    cache: false
    enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/xiaolai?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123
  http:
    multipart:
      enable: true
  servlet:
    multipart:
      max-request-size: 10MB  # 上传文件总的最大值
      max-file-size: 10MB  # 单个文件的最大值

mybatis:
  mapper-locations: classpath:/mapping/*.xml
  config-location: classpath:/mybatis-config.xml
  type-aliases-package: com.cai.xiaolai.entity


#分页插件
pagehelper:
  helper-dialect: mysql
  params: count=countSql
  reasonable: true
  support-methods-arguments: true

file:
  path: E:/Intellij/xiaolai/src/file/

